from pathlib import Path

JARVIS_DIR = Path(r"D:\JARVIS")
DATA_DIR = Path(r"D:\JARVIS_DATA")
LOGS_DIR = JARVIS_DIR / "logs"
PROMPTS_DIR = JARVIS_DIR / "prompts"

SYSTEM_PROMPT_FILE = PROMPTS_DIR / "system.md"
LOG_FILE = LOGS_DIR / "jarvis.log"
MEMORY_FILE = DATA_DIR / "memory" / "facts.txt"
HISTORY_FILE = JARVIS_DIR / "history.json"

OLLAMA_URL = "http://127.0.0.1:11434"
MODEL = "qwen3.5:9b"
NUM_PREDICT = 2000
REQUEST_TIMEOUT = 120
COMMAND_TIMEOUT = 30

WHISPER_MODEL_SIZE = "large-v3"
WHISPER_LANGUAGE = "ru"
WHISPER_DEVICE = "cpu"
WHISPER_COMPUTE = "int8"

PIPER_MODEL = r"D:\JARVIS_DATA\voices\ru_RU-irina-medium.onnx"

MIC_DEVICE = None
SAMPLE_RATE = 16000
CHANNELS = 1
SILENCE_THRESHOLD = 0.01
SILENCE_DURATION = 1.5
MAX_RECORD_SECONDS = 15